Bug 1977307 - Initialize otherwise unused stack variable to appease clang. r=pbone
clang trunk has a new warning that we turn into an error:
```
TestJemalloc.cpp:214:22: error: variable 'stackVar' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
```

Differential Revision: https://phabricator.services.mozilla.com/D257399