Bug 1987713 - Add an explicit AndroidX Concurrency dependency for UI tests. r=android-reviewers,mcarare
Without this, Focus Nightly androidTest builds hit the below error:
ERROR: R8: Missing class androidx.concurrent.futures.SuspendToFutureAdapter (referenced from: com.google.common.util.concurrent.ListenableFuture androidx.test.core.view.ViewCapture.captureToBitmapAsync(android.view.View, android.graphics.Rect) and 1 other context)

Fenix isn't also hitting this because it picks up the Concurrency dependency transitively from other
AC modules. Better to set the dependency explicitly instead to avoid future footguns, however.

Differential Revision: https://phabricator.services.mozilla.com/D264010