Bug 2028826 - Fix disabled efficiency tests that failed to click the toolbar r=jajohnson
The UI tests failed when trying to click the toolbar.
These seem to have been caused by [[ https://phabricator.services.mozilla.com/D266059#change-QXSVYdOkZLfI | this ]] change

Ran the failing tests locally (without the retry rule) and this error was thrown:

```
java.lang.AssertionError: Failed: assertExists. Reason: Expected exactly '1' node but found '2' nodes that satisfy: (TestTag = 'ADDRESSBAR_URL_BOX') Nodes found:
 1) Node #545 at (l=180.0, t=84.0, r=807.0, b=210.0)px, Tag: 'ADDRESSBAR_URL_BOX' ContentDescription = '[Search or enter address]' ClearAndSetSemantics = 'true' Has 1 sibling
2) Node #563 at (l=0.0, t=63.0, r=0.0, b=63.0)px, Tag: 'ADDRESSBAR_URL_BOX' ContentDescription = '[Search or enter address]' ClearAndSetSemantics = 'true'
```

The first node seems to be the corect one, the second one is a invisible helper node that’s being created by compose (for accessibility or layout purposes.)

As Sarah did in her changes, I've switched from using **.onLast** to .**onFirst** to be able to verify and interact with the corect node.

All "efficiency" related UI tests successfully passed 1x on Firebase ✅

Differential Revision: https://phabricator.services.mozilla.com/D291715