Bug 2040285 - Add missing include files for do_CreateInstance.  a=RyanVM
The Thunerbird specific block needs this, otherwise I get
 `toolkit/xre/nsXREDirProvider.cpp:675:11: error: use of undeclared identifier 'do_CreateInstance' `

Original Revision: https://phabricator.services.mozilla.com/D301010

Differential Revision: https://phabricator.services.mozilla.com/D301137