Bug 1775161 - Fix -Wdeprecated-this-capture warnings in netwerk. r=necko-reviewers,valentin
netwerk/ipc/DocumentLoadListener.cpp:975:15: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]

netwerk/protocol/http/nsHttpConnectionMgr.cpp:3011:9 [-Wdeprecated-this-capture] implicit capture of 'this' with a capture default of '=' is deprecated

Differential Revision: https://phabricator.services.mozilla.com/D281490