Bug 1978462 - cherry-pick upstream abseil-cpp commit 66945910. r=ng
Fixes errors:
ERROR -  /builds/worker/checkouts/gecko/third_party/abseil-cpp/absl/time/time.h:1873:12: error: call to non-'constexpr' function 'int64_t absl::operator/(absl::Duration, absl::Duration)'
ERROR -  /builds/worker/checkouts/gecko/third_party/abseil-cpp/absl/time/time.h:1884:12: error: call to non-'constexpr' function 'int64_t absl::operator/(absl::Duration, absl::Duration)'
ERROR -  /builds/worker/checkouts/gecko/third_party/abseil-cpp/absl/time/time.h:1895:12: error: call to non-'constexpr' function 'int64_t absl::operator/(absl::Duration, absl::Duration)'

Differential Revision: https://phabricator.services.mozilla.com/D258099